### ISSUE TITLE
Returning 404 for a `path: /`

### ISSUE THREAD

**Issue by nonsoike** [Frontman-Labs/frontman#90]
The following service configuration returns a 404:

```
# File: /app/services.yaml

- name: client-dashboard
  upstreamTargets:
    - http://client-dashboard:8080
  path: /
  stripPath: false
  ```
