### ISSUE TITLE
Support multiple paths in a service

### ISSUE THREAD

**Issue by nonsoike** [Frontman-Labs/frontman#93]
It will be nice to support multiple `paths` rather than just a single `path` per service.

For example, the following:

```
- name: myservice_v1
  upstreamTargets:
    - http://myservice:7003
  path: /countries
  stripPath: false

- name: myservice_v2
  upstreamTargets:
    - http://myservice:7003
  path: /v2/countries
  stripPath: false
  ```
  
  can be changed to:
  
  ```
- name: myservice
  upstreamTargets:
    - http://myservice:7003
  paths:
    - /countries
    - /v2/countries
  stripPath: false
  ```
